name: "Build and push docker image"
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - uses: actions/checkout@v4.1.1
    - name: set SHORT_SHA
      run: echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        tags: |
          initeq/aws-ecr-helper:latest
          initeq/aws-ecr-helper:${{ env.SHORT_SHA }}
