name: "Build and push docker image"
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: actions/checkout@v2.3.1
    - run: echo "::set-env name=SHORT_SHA::$(git rev-parse --short HEAD)"
    - id: short-sha
      run: echo "::set-output name=short-sha::$(git rev-parse --short HEAD)"
      shell: bash
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          initeq/aws-ecr-helper:latest
          initeq/aws-ecr-helper:${{ steps.short-sha.outputs.short-sha }}
